const { PrismaClient } = require("@prisma/client");
const { PrismaBetterSqlite3 } = require("@prisma/adapter-better-sqlite3");

const adapter = new PrismaBetterSqlite3({ url: "file:./dev.db" });
const prisma = new PrismaClient({ adapter });

const cars = [
  { make: "Tata", model: "Nexon", variant: "XZ+ (O) Dark Edition", price: 1450000, fuelType: "Petrol", transmission: "Automatic", mileage: 17.4, safetyRating: 5.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.2L Turbo Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/141867/nexon-exterior-right-front-three-quarter-2.jpeg", pros: JSON.stringify(["5-star Global NCAP safety", "Feature-rich", "Good ground clearance", "Stylish design"]), cons: JSON.stringify(["Slightly firm ride", "Average highway mileage"]) },
  { make: "Tata", model: "Punch", variant: "Accomplished+ S", price: 1050000, fuelType: "Petrol", transmission: "Automatic", mileage: 18.8, safetyRating: 5.0, bodyType: "Micro SUV", seatingCapacity: 5, engine: "1.2L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/40087/punch-exterior-right-front-three-quarter-3.jpeg", pros: JSON.stringify(["5-star Global NCAP safety", "Compact city car", "Good mileage", "Affordable"]), cons: JSON.stringify(["Small boot space", "Limited rear legroom"]) },
  { make: "Tata", model: "Harrier", variant: "XZA+ Dark Edition", price: 2450000, fuelType: "Diesel", transmission: "Automatic", mileage: 16.35, safetyRating: 5.0, bodyType: "SUV", seatingCapacity: 5, engine: "2.0L Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/42355/harrier-exterior-right-front-three-quarter-3.jpeg", pros: JSON.stringify(["5-star NCAP safety", "Premium interiors", "Powerful diesel engine", "Large cabin"]), cons: JSON.stringify(["Expensive", "No 7-seater option", "High maintenance"]) },
  { make: "Tata", model: "Safari", variant: "XZA+ Gold", price: 2750000, fuelType: "Diesel", transmission: "Automatic", mileage: 14.69, safetyRating: 5.0, bodyType: "SUV", seatingCapacity: 7, engine: "2.0L Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/42355/safari-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star NCAP safety", "7-seater", "Premium feel", "Powerful engine"]), cons: JSON.stringify(["High price", "Heavy fuel consumption", "Large size for city"]) },
  { make: "Tata", model: "Altroz", variant: "XZ+ Dark Edition", price: 1050000, fuelType: "Petrol", transmission: "Manual", mileage: 19.05, safetyRating: 5.0, bodyType: "Hatchback", seatingCapacity: 5, engine: "1.2L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/altroz-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star NCAP safety", "Premium hatchback", "Good mileage", "Solid build"]), cons: JSON.stringify(["No automatic option", "Firm ride", "Average features"]) },
  { make: "Tata", model: "Nexon EV", variant: "Max LR ZX+ Dark", price: 1950000, fuelType: "Electric", transmission: "Automatic", mileage: 0, safetyRating: 5.0, bodyType: "Electric SUV", seatingCapacity: 5, engine: "40.5 kWh Battery", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/nexon-ev-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star safety", "Long range EV", "Zero emissions", "Feature-rich"]), cons: JSON.stringify(["Charging time", "Range anxiety", "High upfront cost"]) },
  { make: "Tata", model: "Tigor EV", variant: "XZ+ Long Range", price: 1350000, fuelType: "Electric", transmission: "Automatic", mileage: 0, safetyRating: 4.0, bodyType: "Sedan", seatingCapacity: 5, engine: "26 kWh Battery", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/tigor-ev-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Affordable EV sedan", "4-star safety", "Zero emissions", "Low running cost"]), cons: JSON.stringify(["Limited range", "Charging time", "Small boot"]) },
  { make: "Mahindra", model: "XUV 3XO", variant: "AX7 L Turbo AT", price: 1650000, fuelType: "Petrol", transmission: "Automatic", mileage: 17.96, safetyRating: 5.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.2L Turbo Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/178093/xuv-3xo-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star NCAP safety", "Feature-loaded", "Panoramic sunroof", "Good performance"]), cons: JSON.stringify(["Slightly expensive", "Rear visibility limited"]) },
  { make: "Mahindra", model: "XUV700", variant: "AX7 L Diesel AT AWD", price: 2850000, fuelType: "Diesel", transmission: "Automatic", mileage: 16.0, safetyRating: 5.0, bodyType: "SUV", seatingCapacity: 7, engine: "2.2L mHawk Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/42355/xuv700-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star NCAP safety", "ADAS features", "Powerful engine", "7-seater"]), cons: JSON.stringify(["Long waiting period", "High price", "Complex tech"]) },
  { make: "Mahindra", model: "Scorpio-N", variant: "Z8 L Diesel MT 4WD", price: 2350000, fuelType: "Diesel", transmission: "Manual", mileage: 15.2, safetyRating: 5.0, bodyType: "SUV", seatingCapacity: 7, engine: "2.2L mHawk Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/130583/scorpio-n-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star NCAP safety", "4WD capability", "Rugged build", "Spacious"]), cons: JSON.stringify(["Firm ride quality", "Large turning radius", "High NVH"]) },
  { make: "Mahindra", model: "Thar", variant: "LX Hard Top Diesel AT 4WD", price: 1850000, fuelType: "Diesel", transmission: "Automatic", mileage: 15.2, safetyRating: 4.0, bodyType: "Off-road SUV", seatingCapacity: 4, engine: "2.2L mHawk Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/thar-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["4-star safety", "4WD off-road", "Iconic design", "Adventure ready"]), cons: JSON.stringify(["Only 4 seats", "Firm ride on road", "Limited boot space"]) },
  { make: "Mahindra", model: "Bolero Neo", variant: "N10 (O) Diesel MT", price: 1250000, fuelType: "Diesel", transmission: "Manual", mileage: 17.29, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 7, engine: "1.5L Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/bolero-neo-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["7-seater", "Good diesel mileage", "Rugged build", "Affordable"]), cons: JSON.stringify(["No automatic", "Basic interiors", "Average safety"]) },
  { make: "Hyundai", model: "Creta", variant: "SX (O) Turbo DCT", price: 2050000, fuelType: "Petrol", transmission: "Automatic", mileage: 16.8, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.4L Turbo Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/106815/creta-exterior-right-front-three-quarter-2.jpeg", pros: JSON.stringify(["Premium interiors", "Smooth DCT gearbox", "Feature-rich", "Good resale value"]), cons: JSON.stringify(["Average safety rating", "Expensive variant", "Turbo lag at low speeds"]) },
  { make: "Hyundai", model: "Venue", variant: "SX (O) Turbo DCT", price: 1450000, fuelType: "Petrol", transmission: "Automatic", mileage: 18.15, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.0L Turbo Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/venue-exterior-right-front-three-quarter-3.jpeg", pros: JSON.stringify(["Good mileage", "Connected car features", "Compact city SUV", "Reliable"]), cons: JSON.stringify(["Average safety rating", "Small boot space", "Rear seat comfort"]) },
  { make: "Hyundai", model: "i20", variant: "Asta (O) Turbo DCT", price: 1250000, fuelType: "Petrol", transmission: "Automatic", mileage: 20.35, safetyRating: 3.0, bodyType: "Hatchback", seatingCapacity: 5, engine: "1.0L Turbo Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/i20-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Excellent mileage", "Premium hatchback", "Sunroof", "Smooth DCT"]), cons: JSON.stringify(["Average safety", "Expensive for hatchback", "Tight rear space"]) },
  { make: "Hyundai", model: "Alcazar", variant: "Signature Diesel AT", price: 2350000, fuelType: "Diesel", transmission: "Automatic", mileage: 17.5, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 7, engine: "1.5L Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/alcazar-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["7-seater", "Premium interiors", "Good diesel mileage", "Feature-rich"]), cons: JSON.stringify(["Average safety rating", "High price", "Slightly underpowered"]) },
  { make: "Hyundai", model: "Exter", variant: "SX (O) AMT", price: 1050000, fuelType: "Petrol", transmission: "Automatic", mileage: 19.4, safetyRating: 3.0, bodyType: "Micro SUV", seatingCapacity: 5, engine: "1.2L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/exter-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Affordable micro SUV", "Good mileage", "Sunroof", "Feature-rich"]), cons: JSON.stringify(["Average safety", "AMT not smooth", "Small boot"]) },
  { make: "Hyundai", model: "Tucson", variant: "Signature Diesel AT AWD", price: 3650000, fuelType: "Diesel", transmission: "Automatic", mileage: 16.0, safetyRating: 5.0, bodyType: "SUV", seatingCapacity: 5, engine: "2.0L Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/tucson-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star safety", "AWD", "Premium SUV", "ADAS features"]), cons: JSON.stringify(["Very expensive", "High maintenance", "Limited service"]) },
  { make: "Kia", model: "Seltos", variant: "GTX+ Turbo DCT", price: 2150000, fuelType: "Petrol", transmission: "Automatic", mileage: 16.5, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.4L Turbo Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/seltos-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Premium features", "Sporty design", "Good performance", "Large touchscreen"]), cons: JSON.stringify(["Average safety rating", "Expensive", "Firm suspension"]) },
  { make: "Kia", model: "Sonet", variant: "GTX+ Turbo DCT", price: 1550000, fuelType: "Petrol", transmission: "Automatic", mileage: 18.2, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.0L Turbo Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/sonet-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Feature-loaded", "Good mileage", "Sporty looks", "Compact SUV"]), cons: JSON.stringify(["Average safety", "Small boot", "Rear seat comfort"]) },
  { make: "Kia", model: "Carens", variant: "Luxury Plus Diesel AT", price: 2050000, fuelType: "Diesel", transmission: "Automatic", mileage: 19.0, safetyRating: 3.0, bodyType: "MPV", seatingCapacity: 7, engine: "1.5L Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/carens-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["7-seater MPV", "Excellent diesel mileage", "Spacious", "Feature-rich"]), cons: JSON.stringify(["Average safety", "Slightly boxy design", "Firm ride"]) },
  { make: "Kia", model: "EV6", variant: "GT Line AWD", price: 6095000, fuelType: "Electric", transmission: "Automatic", mileage: 0, safetyRating: 5.0, bodyType: "Electric SUV", seatingCapacity: 5, engine: "77.4 kWh Battery", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/ev6-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star safety", "AWD performance", "Fast charging", "Premium EV"]), cons: JSON.stringify(["Very expensive", "Limited charging infra", "High insurance"]) },
  { make: "Kia", model: "Carnival", variant: "Limousine Plus Diesel AT", price: 3750000, fuelType: "Diesel", transmission: "Automatic", mileage: 13.4, safetyRating: 4.0, bodyType: "MPV", seatingCapacity: 8, engine: "2.2L Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/carnival-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["8-seater luxury MPV", "Premium interiors", "Powerful diesel", "Spacious"]), cons: JSON.stringify(["Very expensive", "Low mileage", "Large size"]) },
  { make: "Maruti Suzuki", model: "Brezza", variant: "ZXi+ AT", price: 1450000, fuelType: "Petrol", transmission: "Automatic", mileage: 19.8, safetyRating: 4.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.5L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/brezza-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Excellent mileage", "4-star safety", "Low maintenance", "Good resale value"]), cons: JSON.stringify(["No diesel option", "Average performance", "Basic interiors"]) },
  { make: "Maruti Suzuki", model: "Grand Vitara", variant: "Alpha+ Hybrid AT", price: 2050000, fuelType: "Petrol Hybrid", transmission: "Automatic", mileage: 27.97, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.5L Strong Hybrid", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/grand-vitara-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Exceptional mileage", "Strong hybrid tech", "Smooth drive", "Premium feel"]), cons: JSON.stringify(["Average safety rating", "High price", "No diesel option"]) },
  { make: "Maruti Suzuki", model: "Swift", variant: "ZXi+ AMT", price: 950000, fuelType: "Petrol", transmission: "Automatic", mileage: 23.76, safetyRating: 3.0, bodyType: "Hatchback", seatingCapacity: 5, engine: "1.2L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/swift-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Excellent mileage", "Affordable", "Low maintenance", "Fun to drive"]), cons: JSON.stringify(["Average safety", "Small boot", "AMT not smooth"]) },
  { make: "Maruti Suzuki", model: "Baleno", variant: "Alpha CVT", price: 1050000, fuelType: "Petrol", transmission: "Automatic", mileage: 22.35, safetyRating: 2.0, bodyType: "Hatchback", seatingCapacity: 5, engine: "1.2L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/baleno-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Spacious hatchback", "Good mileage", "Smooth CVT", "Feature-rich"]), cons: JSON.stringify(["Low safety rating", "Soft suspension", "Average build quality"]) },
  { make: "Maruti Suzuki", model: "Ertiga", variant: "ZXi+ AT", price: 1450000, fuelType: "Petrol", transmission: "Automatic", mileage: 20.3, safetyRating: 3.0, bodyType: "MPV", seatingCapacity: 7, engine: "1.5L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/ertiga-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["7-seater MPV", "Good mileage", "Affordable", "Spacious"]), cons: JSON.stringify(["Average safety", "Basic interiors", "Underpowered for 7 people"]) },
  { make: "Maruti Suzuki", model: "Fronx", variant: "Alpha Turbo AT", price: 1250000, fuelType: "Petrol", transmission: "Automatic", mileage: 21.79, safetyRating: 2.0, bodyType: "Coupe SUV", seatingCapacity: 5, engine: "1.0L Turbo Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/fronx-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Excellent mileage", "Sporty coupe design", "Turbo performance", "Affordable"]), cons: JSON.stringify(["Low safety rating", "Small boot", "Limited rear headroom"]) },
  { make: "Maruti Suzuki", model: "Jimny", variant: "Zeta AT", price: 1450000, fuelType: "Petrol", transmission: "Automatic", mileage: 16.94, safetyRating: 3.0, bodyType: "Off-road SUV", seatingCapacity: 4, engine: "1.5L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/jimny-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["4WD off-road", "Compact size", "Iconic design", "Good ground clearance"]), cons: JSON.stringify(["Only 4 seats", "Average mileage", "Small cabin"]) },
  { make: "Maruti Suzuki", model: "Dzire", variant: "ZXi+ AMT", price: 1050000, fuelType: "Petrol", transmission: "Automatic", mileage: 24.12, safetyRating: 3.0, bodyType: "Sedan", seatingCapacity: 5, engine: "1.2L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/dzire-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Excellent mileage", "Affordable sedan", "Low maintenance", "Good resale"]), cons: JSON.stringify(["Average safety", "AMT not smooth", "Basic interiors"]) },
  { make: "Toyota", model: "Innova Crysta", variant: "GX Diesel MT", price: 2150000, fuelType: "Diesel", transmission: "Manual", mileage: 15.1, safetyRating: 4.0, bodyType: "MPV", seatingCapacity: 7, engine: "2.4L Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/innova-crysta-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Legendary reliability", "Spacious 7-seater", "Strong diesel engine", "High resale value"]), cons: JSON.stringify(["Dated design", "No automatic option in base", "High price"]) },
  { make: "Toyota", model: "Fortuner", variant: "Legender 4x4 AT", price: 4750000, fuelType: "Diesel", transmission: "Automatic", mileage: 10.0, safetyRating: 4.0, bodyType: "SUV", seatingCapacity: 7, engine: "2.8L Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/fortuner-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Premium SUV", "4x4 capability", "Powerful engine", "High resale value"]), cons: JSON.stringify(["Very expensive", "Low mileage", "Large size"]) },
  { make: "Toyota", model: "Urban Cruiser Hyryder", variant: "V Hybrid AT", price: 2150000, fuelType: "Petrol Hybrid", transmission: "Automatic", mileage: 27.97, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.5L Strong Hybrid", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/urban-cruiser-hyryder-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Exceptional mileage", "Toyota reliability", "Smooth hybrid", "Premium feel"]), cons: JSON.stringify(["Average safety rating", "High price", "Limited boot space"]) },
  { make: "Toyota", model: "Glanza", variant: "V CVT", price: 1050000, fuelType: "Petrol", transmission: "Automatic", mileage: 22.35, safetyRating: 2.0, bodyType: "Hatchback", seatingCapacity: 5, engine: "1.2L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/glanza-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Toyota reliability", "Good mileage", "Smooth CVT", "Feature-rich"]), cons: JSON.stringify(["Low safety rating", "Rebadged Baleno", "Average build"]) },
  { make: "Toyota", model: "Camry", variant: "Hybrid AT", price: 4850000, fuelType: "Petrol Hybrid", transmission: "Automatic", mileage: 19.16, safetyRating: 5.0, bodyType: "Sedan", seatingCapacity: 5, engine: "2.5L Hybrid", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/camry-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star safety", "Luxury hybrid sedan", "Excellent mileage", "Premium feel"]), cons: JSON.stringify(["Very expensive", "High maintenance", "Limited service"]) },
  { make: "Honda", model: "City", variant: "ZX CVT", price: 1750000, fuelType: "Petrol", transmission: "Automatic", mileage: 18.4, safetyRating: 4.0, bodyType: "Sedan", seatingCapacity: 5, engine: "1.5L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/city-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["4-star safety", "Spacious sedan", "Smooth CVT", "Reliable engine"]), cons: JSON.stringify(["No diesel option", "Expensive for segment", "Dated design"]) },
  { make: "Honda", model: "Amaze", variant: "VX CVT", price: 1150000, fuelType: "Petrol", transmission: "Automatic", mileage: 18.6, safetyRating: 4.0, bodyType: "Sedan", seatingCapacity: 5, engine: "1.2L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/amaze-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["4-star safety", "Compact sedan", "Good mileage", "Reliable"]), cons: JSON.stringify(["Small boot", "Average performance", "Basic features"]) },
  { make: "Honda", model: "Elevate", variant: "ZX CVT", price: 1950000, fuelType: "Petrol", transmission: "Automatic", mileage: 15.3, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.5L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/elevate-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Spacious cabin", "Smooth CVT", "Honda reliability", "Good features"]), cons: JSON.stringify(["Average safety rating", "Expensive", "No diesel option"]) },
  { make: "Honda", model: "WR-V", variant: "ZX CVT", price: 1450000, fuelType: "Petrol", transmission: "Automatic", mileage: 16.5, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.5L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/wr-v-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Honda reliability", "Good ground clearance", "Smooth CVT", "Spacious"]), cons: JSON.stringify(["Average safety", "Dated design", "No diesel option"]) },
  { make: "Volkswagen", model: "Taigun", variant: "Topline TSI AT", price: 1950000, fuelType: "Petrol", transmission: "Automatic", mileage: 16.9, safetyRating: 5.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.0L TSI Turbo", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/taigun-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star NCAP safety", "German build quality", "Fun to drive", "Solid construction"]), cons: JSON.stringify(["High maintenance cost", "Expensive service", "Limited dealer network"]) },
  { make: "Volkswagen", model: "Virtus", variant: "Topline TSI AT", price: 1850000, fuelType: "Petrol", transmission: "Automatic", mileage: 19.4, safetyRating: 5.0, bodyType: "Sedan", seatingCapacity: 5, engine: "1.0L TSI Turbo", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/virtus-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star NCAP safety", "German build quality", "Excellent mileage", "Spacious sedan"]), cons: JSON.stringify(["High maintenance", "Expensive service", "Limited features"]) },
  { make: "Volkswagen", model: "Tiguan", variant: "Elegance TSI AT", price: 4850000, fuelType: "Petrol", transmission: "Automatic", mileage: 14.9, safetyRating: 5.0, bodyType: "SUV", seatingCapacity: 5, engine: "2.0L TSI Turbo", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/tiguan-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star safety", "German premium SUV", "Powerful engine", "Premium interiors"]), cons: JSON.stringify(["Very expensive", "High maintenance", "Limited service network"]) },
  { make: "Skoda", model: "Kushaq", variant: "Style TSI AT", price: 2050000, fuelType: "Petrol", transmission: "Automatic", mileage: 16.5, safetyRating: 5.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.5L TSI Turbo", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/kushaq-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star NCAP safety", "Powerful 1.5 TSI", "Premium build", "Fun to drive"]), cons: JSON.stringify(["High maintenance", "Expensive", "Limited dealer network"]) },
  { make: "Skoda", model: "Slavia", variant: "Style TSI AT", price: 1950000, fuelType: "Petrol", transmission: "Automatic", mileage: 19.8, safetyRating: 5.0, bodyType: "Sedan", seatingCapacity: 5, engine: "1.5L TSI Turbo", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/slavia-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star NCAP safety", "Excellent mileage", "Premium sedan", "Powerful engine"]), cons: JSON.stringify(["High maintenance", "Expensive", "Limited service centers"]) },
  { make: "MG", model: "Hector", variant: "Select Pro Diesel AT", price: 2350000, fuelType: "Diesel", transmission: "Automatic", mileage: 16.96, safetyRating: 4.0, bodyType: "SUV", seatingCapacity: 5, engine: "2.0L Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/hector-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Large touchscreen", "Feature-loaded", "Spacious cabin", "Good diesel mileage"]), cons: JSON.stringify(["Average safety", "High price", "Reliability concerns"]) },
  { make: "MG", model: "Astor", variant: "Super CVT", price: 1650000, fuelType: "Petrol", transmission: "Automatic", mileage: 15.02, safetyRating: 4.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.5L Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/astor-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["ADAS features", "AI assistant", "Good safety", "Feature-rich"]), cons: JSON.stringify(["Average mileage", "Reliability concerns", "High maintenance"]) },
  { make: "Renault", model: "Kiger", variant: "RXZ Turbo CVT", price: 1150000, fuelType: "Petrol", transmission: "Automatic", mileage: 20.5, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.0L Turbo Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/kiger-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Affordable SUV", "Good mileage", "Turbo performance", "Stylish design"]), cons: JSON.stringify(["Average safety", "Limited service network", "Reliability concerns"]) },
  { make: "Nissan", model: "Magnite", variant: "Tekna Turbo CVT", price: 1150000, fuelType: "Petrol", transmission: "Automatic", mileage: 20.0, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.0L Turbo Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/magnite-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Affordable SUV", "Good mileage", "Turbo CVT", "Feature-rich"]), cons: JSON.stringify(["Average safety", "Limited service network", "Reliability concerns"]) },
  { make: "Jeep", model: "Meridian", variant: "Limited O AT 4WD", price: 3750000, fuelType: "Diesel", transmission: "Automatic", mileage: 14.0, safetyRating: 5.0, bodyType: "SUV", seatingCapacity: 7, engine: "2.0L Diesel", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/meridian-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["5-star safety", "4WD capability", "Premium 7-seater", "Powerful diesel"]), cons: JSON.stringify(["Very expensive", "High maintenance", "Low mileage"]) },
  { make: "Citroen", model: "C3 Aircross", variant: "Max Turbo AT", price: 1450000, fuelType: "Petrol", transmission: "Automatic", mileage: 16.8, safetyRating: 3.0, bodyType: "SUV", seatingCapacity: 5, engine: "1.2L Turbo Petrol", imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/41652/c3-aircross-exterior-right-front-three-quarter.jpeg", pros: JSON.stringify(["Comfortable ride", "Unique design", "Turbo performance", "Good features"]), cons: JSON.stringify(["Average safety", "Limited service network", "Reliability concerns"]) },
];

async function main() {
  console.log("Seeding database with cars...");
  await prisma.car.deleteMany();
  await prisma.searchHistory.deleteMany();
  for (const car of cars) {
    await prisma.car.create({ data: car });
  }
  console.log(`Successfully seeded ${cars.length} cars!`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
